### ISSUE TITLE
[Kubernetes Deployment] Couldn't send events to siddhi app using minikube IP 

### ISSUE THREAD

**Issue by LakshanSS** [siddhi-io/siddhi-operator#16]
**Description:**
I tried the guide in https://siddhi-io.github.io/siddhi/documentation/siddhi-5.x/siddhi-as-a-kubernetes-microservice-5.x/ using minikube and deployed the monitor-app successfully.

After adding the host **siddhi** and minikube IP to the /etc/hosts file, I was able to sent events to monitor-app using a curl as follows.

curl -X POST \
  https://siddhi/monitor-app/8280/example \
  -H 'Content-Type: application/json' \
  -d '{
    "type": "monitored",
    "deviceID": "001",
    "power": 341
  }' -k

But when I directly used minikube IP in the CURL, I couldn't send events.

I guess this is because the type of the service is ClusterIP and not NodePort. 

Can I get some explanation about this? 
Shall we mention clearly in the doc that we can use only siddhi as the host?

**Affected Version:** 0.1.1

**Comment by BuddhiWathsala** [comment]
The ingress spec that automatically created by the `siddhi-operator`, set the host as `siddhi`. 

Therefore it is better to use `siddhi` host in your request. You can use minikube IP to access the ingress. But when you access using the minikube IP address, ingress does not have an idea that you are trying to access the  `siddhi` host. Thus ingress redirects your request into the default backend. That is why you couldn't access it using minikube IP.

Internally ingress trying to find out the host that you trying to access using `Host` header. So if you really need to send that request using minikube or any IP you have to set that `Host` header in your request as below.

```
curl -X POST \
  https://<MINIKUBE_IP>:<PORT>/monitor-app/8280/example  \
  -H 'Content-Type: application/json' \
  -H 'Host: siddhi' \
  -d '{
    "type": "monitored",
    "deviceID": "001",
    "power": 341
    }' -k
```

Note that if you are using HTTP then use PORT as 80 and for HTTPS use 443. For more reference of the behaviour of host resolving in ingress refer following links.

[1]: https://github.com/kubernetes/ingress-nginx/issues/1803
[2]: https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
