### ISSUE TITLE
Service Implementation to create distributed partial Siddhi apps

### ISSUE THREAD

**Issue by mohanvive** [siddhi-io/siddhi-operator#22]
**Description:**
There should be service which could split a Siddhi app and create partial Siddhi apps by adding necessary messaging system details. Here service should split the Siddhi app based on the annotations used in the queries. This is required for distributed siddhi deployment.

**Comment by BuddhiWathsala** [comment]
In the next release, we are only supporting for siddhi app failover deployments. The failover deployment is a high availability deployment architecture, which used two deployment nodes. The distributed support will eventually be added after that failover support.

**Comment by pcnfernando** [comment]
Created service with https://github.com/siddhi-io/distribution/pull/273.
This PR contains support for failover partial app creation. 
Fully distributed deployment progress is managed through https://github.com/siddhi-io/siddhi-operator/issues/23. Hence, closing.
