### ISSUE TITLE
E2E tests for siddhi operator failover deployment

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#27]
**Description:**
Operator SDK provides an [E2E testing framework](https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md) to test kubernetes operators. Currently, [siddhi operator version 0.1.1](https://github.com/siddhi-io/siddhi-operator/releases/tag/v0.1.1) contained basic E2E tests. It would be better to extend this E2E test into failover deployment level.

**Suggested Labels:**
type/new-feature

**Comment by BuddhiWathsala** [comment]
Currently, siddhi-operator only had E2E tests for default deployment. In the failover scenario, we are planning to implement the E2E test for the following scenarios.

- Check whether automatic NATS creation was successful
- Test the PVC creation of the processing app
- Test the config maps creation (siddhi app deployment config map and configuration change config map)
- Test ingress and service creations.

**Comment by mohanvive** [comment]
Fixed in https://github.com/siddhi-io/siddhi-operator/pull/34 by Buddhi..
