### ISSUE TITLE
Using ConfigMap for Operator Deployment Configs

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#31]
**Description:**
Previously the operator level configurations read as environment variables in the operator deployment. It is better to add a config map to read those configurations instead of using environment variables.

The configurations that read from that config map are,
- siddhiRunnerImage
- autoIngressCreation
- siddhiRunnerHome
- siddhiRunnerImageSecret

**Suggested Labels:**
type/improvement

**Comment by mohanvive** [comment]
Fixed in https://github.com/siddhi-io/siddhi-operator/pull/34 by Buddhi..
