### ISSUE TITLE
*v1.ConfigMap ended with: too old resource version in operator logs

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#41]
**Description:**
When siddhi operator runs in production environments the logs of the siddhi-operator pod prints unwanted logs as below.

```
W0708 07:36:11.095231       1 reflector.go:270] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: watch of *v1.ConfigMap ended with: too old resource version: 858892 (859770)
W0708 07:41:20.112375       1 reflector.go:270] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: watch of *v1.ConfigMap ended with: too old resource version: 860069 (860803)
W0708 07:49:48.123026       1 reflector.go:270] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: watch of *v1.ConfigMap ended with: too old resource version: 861098 (862497)
W0708 07:59:13.139714       1 reflector.go:270] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: watch of *v1.ConfigMap ended with: too old resource version: 862793 (864380)
W0708 08:08:14.160095       1 reflector.go:270] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: watch of *v1.ConfigMap ended with: too old resource version: 864679 (866186)
```

This logs print repeatedly but cannot see any errors in the kubernetes deployments that create by the operator.

**Suggested Labels:**
type/fix

**Affected Product Version:**
siddhi operator version 0.1.0 to 0.2.0-m1

**OS, DB, other environment details and versions:**   
minikube version: v0.33.1 and GKE

**Steps to reproduce:**
1. Install the operator and create a custom object
1. After a while operator log starts to print it.

**Comment by BuddhiWathsala** [comment]
This issue was not actually a siddhi-operator level issue. Instead, this issue happens due to a [kubernetes level issue](https://github.com/kubernetes/kubernetes/issues/22024) but they haven't fix it properly.

**Comment by smiklosovic** [comment]
I have this problem too.

**Comment by BuddhiWathsala** [comment]
@smiklosovic the only solution is just to ignore this issue. As far as I noticed it doesn’t do any harm to your K8s operator. 

I think this might occur when we implement more that one way to update ConfigMaps. If possible it would be better to remove that kind of implementations.

**Comment by domfaber** [comment]
@BuddhiWathsala I have the same issue and my ops-manager-0 pod is stuck at pending forever. I try to deploy Mongo ops manager on AWS EKS cluster. Do you have any idea?

**Comment by BuddhiWathsala** [comment]
@domfaber, my apologies for the late reply. This issue related to a custom K8s resource I have implemented in Siddhi K8s operator. If this problem arise in a pod, I think probably you should double-check the configuration of the pod and the config map.
