### ISSUE TITLE
Cannot deploy WSO2 Streaming Integrator image with different path

### ISSUE THREAD

**Issue by AnuGayan** [siddhi-io/siddhi-operator#52]
**Description:**
When deploying Streaming integrator, we observed a difference in the internal folder structure. 
Difference between siddhi runner paths and Streaming Integrator as follows.
execution file name - 
runner.sh -----------  streaming-integrator.sh

Home path - 
/home/siddhi_user/siddhi-runner/ -------------- /home/wso2carbon/wso2-streaming-integrator/

File persistence location - 
wso2/runner/siddhi-app-persistence ----- wso2/server/siddhi-app-persistence

**Affected Product Version:**
0.2.0-m1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
streaming integrator image - anugayan/streaming-integrator

**Comment by BuddhiWathsala** [comment]
We can change the path that we receive from the config map. Our suggestion would be as follow.

We get two configs as below.
- SiddhiHome = `/home/siddhi_user/siddhi-runner/ `
- Profile = `runner`

Then we use paths like below.
- path to the sh file = `{SiddhiHome} + "bin/" + {Profile} + ".sh"`
- file persistence path = `{SiddhiHome} + {Profile} + "/siddhi-app-persistence"`

In your scenario, you need a common name as the profile.
- SiddhiHome =  `/home/wso2carbon/wso2-streaming-integrator/`
- Profile = `streaming-integrator`

Your paths would be 
- path to the sh file = `/home/wso2carbon/wso2-streaming-integrator/{Profile}.sh`
- file persistence path = `/home/wso2carbon/wso2-streaming-integrator/{Profile}/siddhi-app-persistence"`

Here you need a common name for **Profile**.
