### ISSUE TITLE
Create a deployment screen recording to be included in documentation

### ISSUE THREAD

**Issue by pcnfernando** [siddhi-io/siddhi-operator#63]
**Description:**
Need to create a recording of a Siddhi app being deployed as a Siddhi custom resource object to kubernetes to be added to http://siddhi.io

**Comment by mohanvive** [comment]
@pcnfernando Shall we add the video created by Suho for this.
https://www.youtube.com/watch?v=e7xo2pO0DXg&feature=youtu.be

**Comment by mohanvive** [comment]
Added in https://github.com/siddhi-io/www/pull/78 ...
