### ISSUE TITLE
SiddhiProcess consumes more time to deploy due to the dynamic parser implementation

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#79]
**Description:**
Before 0.2.0-m2 release Siddhi operator used a static parser which deployed as a prerequisite. If a user has a custom extension that static parser would fail. Therefore in 0.2.0-m2 contained a dynamic parser which used in the runtime. That dynamic parser is nothing but another Siddhi runner deployment with extra parameters. The dynamic parser works as follow.

1. Deploy Siddhi runner image with an external service
1. Invoke the parser and parse the Siddhi apps
1. Destroy the deployments and services

In previous static parser did only the parsing functionality. Therefore this dynamic parser takes more time to parse a Siddhi app. Hence the SiddhiProcess deployments also delayed a bit compared to previous implementations.

**Suggested Labels:**
Feature improvement

**Affected Product Version:**
0.2.0-m2

**Comment by mohanvive** [comment]
Won't fix..
