### ISSUE TITLE
Make SiddhiProcess status running when pods become available

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#80]
**Description:**
Currently, SiddhiProcesses comes to the Running state when all the deployments and services up and running. But after the creation of deployment, it takes some extra time to becomes pods available.

It is better if SiddhiProcesses comes to a Running state after pods become available.

**Suggested Labels:**
Feature improvement

**Affected Product Version:**
0.2.0-m2

**Comment by mohanvive** [comment]
Add a status as 'Health-Check' for the event.
